### PR TITLE
Upgrading Buildtools, Java 11 and Liquibase

### PR DESCRIPTION
**Pull request by petrchiriboga**
Hi @michaljonko,

I'm interested into update this **_awesome_** work to a current stable baseline of frameworks,
would you mind please review it and let me know any comments and suggestions, Thank you so much.

## Changes

- [feat: Upgrade to Gradle 7.6](https://github.com/michaljonko/GuiceLiquibase/commit/1b04a25f1a5664b8420bb9124fc8e12799611fc2) 
- [chore: Upgrade checkstyle and fix checks](https://github.com/michaljonko/GuiceLiquibase/commit/e30a3979173543eb8adce79df9d832e6999945d1) 
- [feat: Adding SpotBugs instead of FindBugs](https://github.com/michaljonko/GuiceLiquibase/commit/92818e21493ee6f84b87c2f7aceef60c9bceb435) 
- [feat: Upgrade Mockito and Hamcrest](https://github.com/michaljonko/GuiceLiquibase/commit/1506dc619bad7931889d4918ab1fbb2d0d98fd37) 
- [feat: Upgrade ThirdParty Libraries](https://github.com/michaljonko/GuiceLiquibase/commit/5ca275c9cfb0b008f78478b515e53ea88616ecbc) 
- [feat: Upgrade to Java 11](https://github.com/michaljonko/GuiceLiquibase/commit/9d30900ae48e0999d40c5bd388a762f7a758f899) 
- [feat: Upgrade Checkstyle and Mockito to Java 11 versions](https://github.com/michaljonko/GuiceLiquibase/commit/844f0e5bfb35809f665b6d065c055260605a5521) 
- [feat: Migrate Libraries to Junit 5](https://github.com/michaljonko/GuiceLiquibase/commit/88c72fcbe0aaaf433c6233f27eb61207e061672b) 
- [feat: Upgrade Testcases to JUnit 5](https://github.com/michaljonko/GuiceLiquibase/commit/7f6111a622fab4e6e9b3d3d2b8455ad4e850e0c6) 
- [feat: Upgrade Liquibase to 4.20.0](https://github.com/michaljonko/GuiceLiquibase/commit/2a3c781a7b9c487aebc499203b5918a9f282881f) 
- [feat: Configure gradle publish to Sonatype](https://github.com/michaljonko/GuiceLiquibase/commit/78418415e7f10943483720fd5db49cf8ea44e067)

### CODE REVIEW

**Comment by michaljonko** [comment]
I'll try to review it this week. For small improvements/comments I'll try to change it and push to your branch.

**Comment by petrchiriboga** [comment]
> I'll try to review it this week. For small improvements/comments I'll try to change it and push to your branch.

This is great news,  I've just added a fix on the Gradle Sonatype Publishing that needed to be tested.

[fix: Publishing to Sonatype](https://github.com/michaljonko/GuiceLiquibase/pull/1/commits/59d3a4e73cc0e8286149ad80baf32c44bcbfb2d7)

Thank you so much!

**Comment by michaljonko** [comment]
@petrchiriboga 
I've started to review it and also apply some changes (use jupiter + assertj only, etc.). I'll push the commit with changes as a part of your PR (to not wait for comments). One thing I would like to mention: I'll change compatibility to JVM 8 - still I think it will be a good base for old projects that would like to use it.

**Comment by petrchiriboga** [comment]
> @petrchiriboga I've started to review it and also apply some changes (use jupiter + assertj only, etc.). I'll push the commit with changes as a part of your PR (to not wait for comments). 

Sure, no problem it makes sense

> One thing I would like to mention: I'll change compatibility to JVM 8 - still I think it will be a good base for old projects that would like to use it.

Sure, fare enough I thought on upgrading to 0.1.0 then do the upgrade, I can see some libraries moving away from Java 8 and keeping legacy branches with older versions.

that could be another option as well.

**Comment by michaljonko** [comment]
Hi!
I have no access to push my changes on the branch to the forked remote repo. I pushed 1st part of the changes here https://github.com/michaljonko/GuiceLiquibase/tree/feat/upgrade_baseline
Only checkstyle + spotbugs left to apply on those changes (need to prepare another commit)

**Comment by michaljonko** [comment]
I can push those changes but you need to grant permissions to me

**Comment by petrchiriboga** [comment]
> I can push those changes but you need to grant permissions to me

I have given you access to it, 

We can work in this PR or in your branch (and close this) happy to follow what's best.

**Comment by michaljonko** [comment]
> > I can push those changes but you need to grant permissions to me
> 
> I have given you access to it,
> 
> We can work in this PR or in your branch (and close this) happy to follow what's best.

Not sure but stil cannot push changes to the remote repo and that branch - not sure if it can help https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

You can synchronize the same branch from mine repo - could work fine.

**Comment by petrchiriboga** [comment]
> > > I can push those changes but you need to grant permissions to me
> > 
> > 
> > I have given you access to it,
> > We can work in this PR or in your branch (and close this) happy to follow what's best.
> 
> Not sure but stil cannot push changes to the remote repo and that branch - not sure if it can help https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> You can synchronize the same branch from mine repo - could work fine.

In theory everything should be in place
Screen Shot 2023-10-04 at 10 17 40 am

I've resync the fork as well in case 😄

**Comment by michaljonko** [comment]
@petrchiriboga 
I think that all changes from my side are done.
Please review them as a combine mine & your work.
If there will be no major issues, I'll merge it and publish a new release - maven central + github.

**Review by petrchiriboga — COMMENTED** [review]
This looks in order 🤘 , thank you so much for spending more time on this, its really valuable.
🚀

**Review by michaljonko — APPROVED** [review]

**Pull request merged**
